Added creation user function #(4-create-user-function)
trayl-app/monviso pull request #5
Opened 2022-10-09 17:32 UTC by carlodenardin

2022-10-09 20:09 UTC, carlodenardin commented on src/users/users.controller.ts
> +  @Post(':createUser')
Con solo @Post() poi la chiamata sarà localhost:3000/users ?

2022-10-09 20:11 UTC, carlodenardin commented on src/users/users.repository.ts
> +  async create(newUser: User): Promise<User | null> {
intendi il tipo del `newUser`?

2022-10-09 20:12 UTC, ocintnaf commented on src/users/users.repository.ts
> +  async create(newUser: User): Promise<User | null> {
![image](https://user-images.githubusercontent.com/79849332/194777545-15f781eb-5ade-49bc-855c-57d0feddd8be.jpeg)

si

2022-10-10 06:24 UTC, ocintnaf commented on src/users/users.controller.ts
>    createUser(@Body() newUser: User) {
deve andare qua il dto, non sulla repository

2022-10-10 06:28 UTC, ocintnaf commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
andrebbe aggiunto un metodo per trasformare il dto in entity

2022-10-10 06:31 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
Fallo te

2022-10-10 06:31 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
ho sistemato il tipo sto nel controller

2022-10-10 07:40 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
Intendi così? [stackoverflow](https://stackoverflow.com/questions/63244163/nestjs-do-i-need-dtos-along-with-entities) prima risposta

2022-10-10 07:42 UTC, ocintnaf commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
boh

2022-10-10 07:44 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
Che poi non viene mappato automaticamente?

2022-10-10 07:46 UTC, ocintnaf commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
ah forse si, si può fare come su quella domanda di stack

2022-10-10 07:46 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
provo a sistemare io allora

2022-10-10 08:14 UTC, carlodenardin commented on src/users/dto/create-user.dto.ts
> -export class CreateUserDto {}
Boh non ci capisco an casso. Ho pushato, sistema te e chiudi la issue.

2022-10-10 12:44 UTC, ocintnaf requested changes
bitch ass

2022-10-11 05:25 UTC, merged